- name: Create temporary directory
  tempfile:
    state: directory
  register: temp_dir

- name: Download Snow rpm {{ resource_bucket_snow_prefix }}/snow-{{ snow_version }}-x86_64.rpm
  vars:
    ansible_python_interpreter: "{{ python_interpreter }}"
  aws_s3:
    bucket: "{{ resource_bucket_name }}"
    object: "{{ resource_bucket_snow_prefix }}/snow-{{ snow_version }}-x86_64.rpm"
    dest: "{{ temp_dir.path }}/snow-{{ snow_version }}-x86_64.rpm"
    mode: get

- name: Install rpm {{ temp_dir.path }}/snow-{{ snow_version }}-x86_64.rpm
  yum:
    name: "{{ temp_dir.path }}/snow-{{ snow_version }}-x86_64.rpm"
    state: present

- name: Remove temporary directory
  file:
    path: temp_dir.path
    state: absent