---
- name: Copy rpm file to server.
  copy:
     src: files/COMPANIESHOUSE-snowagent-6.4.1-x64.rpm
     dest: /tmp/COMPANIESHOUSE-snowagent-6.4.1-x64.rpm

- name: Install package.
  package:
     name: /tmp/COMPANIESHOUSE-snowagent-6.4.1-x64.rpm
     state: present
     disable_gpg_check: yes

- name: Copy snow config and set h owner and permissions
  ansible.builtin.copy:
    src: files/snowagent.config
    dest: /opt/snow/snowagent.config
    owner: root
    group: root
    mode: '0600'
    backup: yes
